# Generated by Django 4.2.10 on 2024-04-12 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0004_alter_goods_category_alter_goods_upload_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paragraph", models.TextField(verbose_name="Абзац тексту")),
                (
                    "paragraph_image",
                    models.ImageField(upload_to="", verbose_name="Фото до абзацу"),
                ),
                (
                    "category",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.categories",
                        verbose_name="Категорія",
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "Продукцію",
                "db_table": "product",
            },
        ),
    ]
