# Generated by Django 4.2.10 on 2024-09-06 16:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0006_categories_name_ru_goods_description_ru_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "index_on_page",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Порядковий номер",
                    ),
                ),
                ("paragraph", models.TextField(verbose_name="Основний текст")),
                (
                    "paragraph_uk",
                    models.TextField(null=True, verbose_name="Основний текст"),
                ),
                (
                    "paragraph_en",
                    models.TextField(null=True, verbose_name="Основний текст"),
                ),
                (
                    "paragraph_ru",
                    models.TextField(null=True, verbose_name="Основний текст"),
                ),
                (
                    "paragraph_image",
                    models.ImageField(
                        upload_to="categories_images",
                        verbose_name="Фото до основного тексту",
                    ),
                ),
                (
                    "addition_paragraph",
                    models.TextField(
                        blank=True, null=True, verbose_name="Додатковий текст"
                    ),
                ),
                (
                    "addition_paragraph_uk",
                    models.TextField(
                        blank=True, null=True, verbose_name="Додатковий текст"
                    ),
                ),
                (
                    "addition_paragraph_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Додатковий текст"
                    ),
                ),
                (
                    "addition_paragraph_ru",
                    models.TextField(
                        blank=True, null=True, verbose_name="Додатковий текст"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Назва сторінки",
                    ),
                ),
                (
                    "title_uk",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Назва сторінки",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Назва сторінки",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Назва сторінки",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Опис для метатегу"
                    ),
                ),
                (
                    "description_uk",
                    models.TextField(
                        blank=True, null=True, verbose_name="Опис для метатегу"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Опис для метатегу"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        blank=True, null=True, verbose_name="Опис для метатегу"
                    ),
                ),
                (
                    "category",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.categories",
                        verbose_name="Категорія",
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "Продукцію",
                "db_table": "product",
            },
        ),
        migrations.CreateModel(
            name="ProductVideos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    embed_video.fields.EmbedVideoField(
                        verbose_name="Посилання на відео"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                        verbose_name="Категорія",
                    ),
                ),
            ],
            options={
                "verbose_name": "відео продукції",
                "verbose_name_plural": "Відео продукції",
                "db_table": "product_videos",
            },
        ),
        migrations.CreateModel(
            name="ProductPhotos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="categories_images", verbose_name="Фото"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                        verbose_name="Категорія",
                    ),
                ),
            ],
            options={
                "verbose_name": "фото продукції",
                "verbose_name_plural": "Фото продукції",
                "db_table": "product_photo",
            },
        ),
        migrations.CreateModel(
            name="ProductCharacteristics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Назва характеристики"
                    ),
                ),
                (
                    "name_uk",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Назва характеристики"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Назва характеристики"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Назва характеристики"
                    ),
                ),
                ("description", models.CharField(max_length=255, verbose_name="Опис")),
                (
                    "description_uk",
                    models.CharField(max_length=255, null=True, verbose_name="Опис"),
                ),
                (
                    "description_en",
                    models.CharField(max_length=255, null=True, verbose_name="Опис"),
                ),
                (
                    "description_ru",
                    models.CharField(max_length=255, null=True, verbose_name="Опис"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                        verbose_name="Категорія",
                    ),
                ),
            ],
            options={
                "verbose_name": "характеристика продукції",
                "verbose_name_plural": "Характеристики продукції",
                "db_table": "products_characteristics",
            },
        ),
    ]
