# Generated by Django 4.2.10 on 2024-04-12 11:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_goods_category_alter_goods_upload_time"),
        ("product", "0002_product_paragraph_en_product_paragraph_uk"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="index_on_page",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Порядковий номер",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.categories",
                verbose_name="Категорія",
            ),
        ),
    ]
