# Generated by Django 4.2.10 on 2024-04-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_product_index_on_page_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="paragraph_image",
            field=models.ImageField(
                upload_to="categories_images", verbose_name="Фото до абзацу"
            ),
        ),
    ]
