# Generated by Django 4.2.10 on 2024-04-12 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_goods_category_alter_goods_upload_time"),
        ("product", "0004_alter_product_paragraph_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.categories",
                verbose_name="Категорія",
            ),
        ),
    ]
