# Generated by Django 4.2.10 on 2024-04-12 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "index_on_page",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Порядковий номер",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(max_length=200, verbose_name="Назва послуги"),
                ),
                (
                    "service_name_uk",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Назва послуги"
                    ),
                ),
                (
                    "service_name_en",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Назва послуги"
                    ),
                ),
                ("service_description", models.TextField(verbose_name="Опис послуги")),
                (
                    "service_description_uk",
                    models.TextField(null=True, verbose_name="Опис послуги"),
                ),
                (
                    "service_description_en",
                    models.TextField(null=True, verbose_name="Опис послуги"),
                ),
                (
                    "service_image",
                    models.ImageField(
                        upload_to="services_images", verbose_name="Фото послуги"
                    ),
                ),
            ],
            options={
                "verbose_name": "сервіс",
                "verbose_name_plural": "Сервіси",
                "db_table": "service",
            },
        ),
    ]
