# Generated by Django 4.2.10 on 2024-04-16 18:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_goods_category_alter_goods_upload_time"),
        ("product", "0006_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="index_on_page",
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.categories",
                verbose_name="Категорія",
            ),
        ),
        migrations.CreateModel(
            name="ProductVideos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    embed_video.fields.EmbedVideoField(
                        verbose_name="Посилання на відео"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                        verbose_name="Категорія",
                    ),
                ),
            ],
            options={
                "verbose_name": "відео продукції",
                "verbose_name_plural": "Відео продукції",
                "db_table": "product_videos",
            },
        ),
        migrations.CreateModel(
            name="ProductPhotos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="categories_images", verbose_name="Фото"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                        verbose_name="Категорія",
                    ),
                ),
            ],
            options={
                "verbose_name": "фото продукції",
                "verbose_name_plural": "Фото продукції",
                "db_table": "product_photo",
            },
        ),
        migrations.CreateModel(
            name="ProductParagraphs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "index_on_page",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Порядковий номер",
                    ),
                ),
                ("paragraph", models.TextField(verbose_name="Абзац")),
                ("paragraph_uk", models.TextField(null=True, verbose_name="Абзац")),
                ("paragraph_en", models.TextField(null=True, verbose_name="Абзац")),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                        verbose_name="Категорія",
                    ),
                ),
            ],
            options={
                "verbose_name": "абзац продукції",
                "verbose_name_plural": "Абзаци продукції",
                "db_table": "product_paragraphs",
            },
        ),
        migrations.CreateModel(
            name="ProductCharacteristics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Назва характеристики"
                    ),
                ),
                (
                    "name_uk",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Назва характеристики"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Назва характеристики"
                    ),
                ),
                ("description", models.CharField(max_length=255, verbose_name="Опис")),
                (
                    "description_uk",
                    models.CharField(max_length=255, null=True, verbose_name="Опис"),
                ),
                (
                    "description_en",
                    models.CharField(max_length=255, null=True, verbose_name="Опис"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                        verbose_name="Категорія",
                    ),
                ),
            ],
            options={
                "verbose_name": "характеристика продукції",
                "verbose_name_plural": "Характеристики продукції",
                "db_table": "products_characteristics",
            },
        ),
    ]
