# Generated by Django 4.2.10 on 2024-04-16 22:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product",
            "0007_remove_product_index_on_page_alter_product_category_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="index_on_page",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Порядковий номер",
            ),
        ),
    ]
