# Generated by Django 4.2.10 on 2024-04-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_product_index_on_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="addition_paragraph",
            field=models.TextField(
                blank=True, null=True, verbose_name="Додатковий текст"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="addition_paragraph_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Додатковий текст"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="addition_paragraph_uk",
            field=models.TextField(
                blank=True, null=True, verbose_name="Додатковий текст"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="paragraph",
            field=models.TextField(verbose_name="Основний текст"),
        ),
        migrations.AlterField(
            model_name="product",
            name="paragraph_en",
            field=models.TextField(null=True, verbose_name="Основний текст"),
        ),
        migrations.AlterField(
            model_name="product",
            name="paragraph_image",
            field=models.ImageField(
                upload_to="categories_images", verbose_name="Фото до основного тексту"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="paragraph_uk",
            field=models.TextField(null=True, verbose_name="Основний текст"),
        ),
        migrations.DeleteModel(
            name="ProductParagraphs",
        ),
    ]
