# Generated by Django 4.2.10 on 2024-08-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_product_addition_paragraph_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="addition_paragraph_ru",
            field=models.TextField(
                blank=True, null=True, verbose_name="Додатковий текст"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="paragraph_ru",
            field=models.TextField(null=True, verbose_name="Основний текст"),
        ),
        migrations.AddField(
            model_name="productcharacteristics",
            name="description_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Опис"),
        ),
        migrations.AddField(
            model_name="productcharacteristics",
            name="name_ru",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Назва характеристики"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="service_description_ru",
            field=models.TextField(null=True, verbose_name="Опис послуги"),
        ),
        migrations.AddField(
            model_name="service",
            name="service_name_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Назва послуги"
            ),
        ),
    ]
