# Generated by Django 4.2.10 on 2024-09-05 20:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Solution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "solution_title",
                    models.CharField(max_length=250, verbose_name="Назва сервісу"),
                ),
                (
                    "solution_title_uk",
                    models.CharField(
                        max_length=250, null=True, verbose_name="Назва сервісу"
                    ),
                ),
                (
                    "solution_title_en",
                    models.CharField(
                        max_length=250, null=True, verbose_name="Назва сервісу"
                    ),
                ),
                (
                    "solution_title_ru",
                    models.CharField(
                        max_length=250, null=True, verbose_name="Назва сервісу"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, null=True, unique=True, verbose_name="URL"
                    ),
                ),
                (
                    "index_on_page",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Порядковий номер",
                    ),
                ),
                ("review_content", models.TextField(verbose_name="Вступний текст")),
                (
                    "review_content_uk",
                    models.TextField(null=True, verbose_name="Вступний текст"),
                ),
                (
                    "review_content_en",
                    models.TextField(null=True, verbose_name="Вступний текст"),
                ),
                (
                    "review_content_ru",
                    models.TextField(null=True, verbose_name="Вступний текст"),
                ),
                (
                    "review_image",
                    models.ImageField(
                        upload_to="solution_images",
                        verbose_name="Фото до вступного тексту",
                    ),
                ),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Контент"
                    ),
                ),
                (
                    "content_uk",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Контент"
                    ),
                ),
                (
                    "content_en",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Контент"
                    ),
                ),
                (
                    "content_ru",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Контент"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Назва сторінки",
                    ),
                ),
                (
                    "title_uk",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Назва сторінки",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Назва сторінки",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Назва сторінки",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Опис для метатегу"
                    ),
                ),
                (
                    "description_uk",
                    models.TextField(
                        blank=True, null=True, verbose_name="Опис для метатегу"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Опис для метатегу"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        blank=True, null=True, verbose_name="Опис для метатегу"
                    ),
                ),
            ],
            options={
                "verbose_name": "послуга",
                "verbose_name_plural": "Послуги",
                "db_table": "solution",
            },
        ),
        migrations.CreateModel(
            name="SolutionVideos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    embed_video.fields.EmbedVideoField(
                        verbose_name="Посилання на відео"
                    ),
                ),
                (
                    "solution",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solution.solution",
                        verbose_name="Послуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "відео послуги",
                "verbose_name_plural": "Відео послуги",
                "db_table": "solution_videos",
            },
        ),
        migrations.CreateModel(
            name="SolutionPhotos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="solution_images", verbose_name="Фото"),
                ),
                (
                    "solution",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solution.solution",
                        verbose_name="Послуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "фото послуги",
                "verbose_name_plural": "Фото послуги",
                "db_table": "solution_photo",
            },
        ),
    ]
