# Generated by Django 4.2.10 on 2024-04-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0002_alter_vacancy_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancydescription",
            name="choice_en",
        ),
        migrations.RemoveField(
            model_name="vacancydescription",
            name="choice_uk",
        ),
    ]
