# Generated by Django 4.2.10 on 2024-04-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0003_remove_vacancydescription_choice_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancydescription",
            name="choice",
            field=models.IntegerField(
                choices=[(1, "Вимоги"), (2, "Обов'язки"), (3, "Умови"), (4, "Від нас")],
                verbose_name="Виберіть",
            ),
        ),
    ]
