# Generated by Django 4.2.10 on 2024-08-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0004_alter_vacancydescription_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="position_ru",
            field=models.CharField(
                max_length=150, null=True, verbose_name="Назва вакансії"
            ),
        ),
        migrations.AddField(
            model_name="vacancydescription",
            name="text_ru",
            field=models.TextField(null=True, verbose_name="Введіть інформацію"),
        ),
    ]
