# Generated by Django 4.2.10 on 2024-04-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientMessages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Ім'я")),
                (
                    "number_or_email",
                    models.CharField(max_length=200, verbose_name="Номер або email"),
                ),
                ("message", models.TextField(verbose_name="Повідомлення")),
            ],
            options={
                "verbose_name": "повідомлення клієнта",
                "verbose_name_plural": "Повідомлення клієнтів",
                "db_table": "client_message",
            },
        ),
    ]
