# Generated by Django 4.2.10 on 2024-04-11 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientmessages",
            name="send_message_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата повідомлення",
            ),
            preserve_default=False,
        ),
    ]
