# Generated by Django 4.2.10 on 2024-08-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_clientmessages_send_message_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientmessages",
            name="message",
            field=models.TextField(
                blank=True,
                default="Повідомлення не вказано",
                null=True,
                verbose_name="Повідомлення",
            ),
        ),
        migrations.AlterField(
            model_name="clientmessages",
            name="name",
            field=models.CharField(
                blank=True,
                default="Ім'я не вказано",
                max_length=150,
                null=True,
                verbose_name="Ім'я",
            ),
        ),
    ]
