# Generated by Django 4.2.10 on 2024-04-10 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodsCharacteristic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Назва характеристики"
                    ),
                ),
                ("value", models.CharField(max_length=255, verbose_name="Опис")),
                (
                    "good",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.goods",
                    ),
                ),
            ],
            options={
                "verbose_name": "характеристика товару",
                "verbose_name_plural": "Характеристики товару",
                "db_table": "goods_characteristics",
            },
        ),
    ]
