# Generated by Django 4.2.10 on 2024-04-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_goodscharacteristic"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goodscharacteristic",
            old_name="value",
            new_name="description",
        ),
        migrations.AddField(
            model_name="goodscharacteristic",
            name="description_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Опис"),
        ),
        migrations.AddField(
            model_name="goodscharacteristic",
            name="description_uk",
            field=models.CharField(max_length=255, null=True, verbose_name="Опис"),
        ),
        migrations.AddField(
            model_name="goodscharacteristic",
            name="name_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Назва характеристики"
            ),
        ),
        migrations.AddField(
            model_name="goodscharacteristic",
            name="name_uk",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Назва характеристики"
            ),
        ),
    ]
