# Generated by Django 4.2.10 on 2024-04-12 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_rename_value_goodscharacteristic_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goods",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.categories",
                verbose_name="Категорія",
            ),
        ),
        migrations.AlterField(
            model_name="goods",
            name="upload_time",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата завантаження"
            ),
        ),
    ]
