# Generated by Django 4.2.10 on 2024-04-16 22:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_goods_category_alter_goods_upload_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="index_on_page",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Порядковий номер",
            ),
        ),
    ]
