# Generated by Django 4.2.10 on 2024-09-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_categories_name_ru_goods_description_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="currency",
            field=models.CharField(
                choices=[("$", "Долар"), ("€", "Євро"), ("₴", "Гривня")],
                default="$",
                max_length=1,
                verbose_name="Валюта",
            ),
        ),
        migrations.AddField(
            model_name="goods",
            name="meta_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Опис для метатегу"
            ),
        ),
        migrations.AddField(
            model_name="goods",
            name="meta_description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Опис для метатегу"
            ),
        ),
        migrations.AddField(
            model_name="goods",
            name="meta_description_ru",
            field=models.TextField(
                blank=True, null=True, verbose_name="Опис для метатегу"
            ),
        ),
        migrations.AddField(
            model_name="goods",
            name="meta_description_uk",
            field=models.TextField(
                blank=True, null=True, verbose_name="Опис для метатегу"
            ),
        ),
        migrations.AddField(
            model_name="goods",
            name="meta_title",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Назва сторінки товару",
            ),
        ),
        migrations.AddField(
            model_name="goods",
            name="meta_title_en",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Назва сторінки товару",
            ),
        ),
        migrations.AddField(
            model_name="goods",
            name="meta_title_ru",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Назва сторінки товару",
            ),
        ),
        migrations.AddField(
            model_name="goods",
            name="meta_title_uk",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Назва сторінки товару",
            ),
        ),
        migrations.AddField(
            model_name="goods",
            name="preview_alt",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Alt зображення",
            ),
        ),
        migrations.AddField(
            model_name="goods",
            name="preview_alt_en",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Alt зображення",
            ),
        ),
        migrations.AddField(
            model_name="goods",
            name="preview_alt_ru",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Alt зображення",
            ),
        ),
        migrations.AddField(
            model_name="goods",
            name="preview_alt_uk",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Alt зображення",
            ),
        ),
        migrations.AddField(
            model_name="goodsimage",
            name="alt",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Alt зображення",
            ),
        ),
        migrations.AddField(
            model_name="goodsimage",
            name="alt_en",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Alt зображення",
            ),
        ),
        migrations.AddField(
            model_name="goodsimage",
            name="alt_ru",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Alt зображення",
            ),
        ),
        migrations.AddField(
            model_name="goodsimage",
            name="alt_uk",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Alt зображення",
            ),
        ),
    ]
