# Generated by Django 4.2.10 on 2024-09-12 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_goods_currency_goods_meta_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goods",
            name="currency",
        ),
    ]
