# Generated by Django 4.2.10 on 2024-04-10 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Ім'я")),
                ("surname", models.CharField(max_length=50, verbose_name="Прізвище")),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Номер телефону"),
                ),
                ("email", models.CharField(max_length=70, verbose_name="Email")),
                ("city", models.CharField(max_length=30, verbose_name="Місто")),
                (
                    "delivery_address",
                    models.CharField(max_length=100, verbose_name="Адреса доставки"),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Повідомлення"
                    ),
                ),
                (
                    "created_timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення замовлення"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="В обробці",
                        max_length=50,
                        verbose_name="Статус замовлення",
                    ),
                ),
            ],
            options={
                "verbose_name": "замовлення",
                "verbose_name_plural": "Замовлення",
                "db_table": "order",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Назва")),
                ("price", models.FloatField(verbose_name="Ціна")),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Кількість"),
                ),
                (
                    "created_timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата продажі"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.orderdetails",
                        verbose_name="Замовлення",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="catalog.goods",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проданий товар",
                "verbose_name_plural": "Продані товари",
                "db_table": "order_item",
            },
        ),
    ]
